DELETE FROM TIME;

INSERT INTO TIME (NOME, ESTADO, TIPO, SALDO_GOLS) VALUES ('Cruzeiro', 'SP', 'amador', 10);
INSERT INTO TIME (NOME, ESTADO, TIPO, SALDO_GOLS) VALUES ('São Paulo', 'SP', 'profissional', 5);
INSERT INTO TIME (NOME, ESTADO, TIPO, SALDO_GOLS) VALUES ('Corinthians', 'SP', 'profissional', 10);
INSERT INTO TIME (NOME, ESTADO, TIPO, SALDO_GOLS) VALUES ('Palmeira', 'SP', 'profissional', 10);

SELECT * FROM TIME;

UPDATE TIME SET NOME = 'Palmeiras' WHERE NOME = 'Palmeira';
UPDATE TIME SET TIPO = 'profissional' WHERE NOME = 'Cruzeiro';

SELECT * FROM TIME;

INSERT INTO JOGA (TIME1, TIME2, CLASSICO) VALUES ('Palmeiras', 'São Paulo', 'S');
INSERT INTO JOGA (TIME1, TIME2, CLASSICO) VALUES ('Palmeiras', 'Palmeiras', 'N');
INSERT INTO JOGA (TIME1, TIME2, CLASSICO) VALUES ('Palmeiras', 'Corinthians', 'S');

SELECT * FROM JOGA;

INSERT INTO PARTIDA (TIME1, TIME2, DATA, PLACAR) VALUES ('Palmeiras', 'São Paulo', TO_DATE('04/12/2022 15:00:00', 'dd/mm/yyyy hh24:mi:ss'), '10x0');
INSERT INTO PARTIDA (TIME1, TIME2, DATA) VALUES ('Palmeiras', 'Corinthians', TO_DATE('05/12/2022 15:00:00', 'dd/mm/yyyy hh24:mi:ss'));
INSERT INTO PARTIDA (TIME1, TIME2, DATA, PLACAR) VALUES ('Palmeiras', 'Corinthians', TO_DATE('07/12/2022 15:00:00', 'dd/mm/yyyy hh24:mi:ss'), '5X6');

SELECT * FROM PARTIDA;

INSERT INTO JOGADOR (CPF, RG, NOME, DATA_NASC, NATURALIDADE, TIME) VALUES ('123.456.789.25', '562364582', 'JAMAS', TO_DATE('06/07/2000', 'DD/mm/yyyy'), 'Araracity', 'Corinthians');
INSERT INTO JOGADOR (CPF, RG, NOME, DATA_NASC, NATURALIDADE, TIME) VALUES ('456.456.789.25', '562364582', 'VINIL', TO_DATE('06/07/2000', 'DD/mm/yyyy'), 'Araracity', 'Corinthians');

SELECT * FROM JOGADOR;

INSERT INTO POSICAO_JOGADOR (JOGADOR, POSICAO) VALUES ('123.456.789.25', 'centro');
INSERT INTO POSICAO_JOGADOR (JOGADOR, POSICAO) VALUES ('123.456.789.25', 'lateral');
INSERT INTO POSICAO_JOGADOR (JOGADOR, POSICAO) VALUES ('456.456.789.25', 'lateral');

SELECT * FROM POSICAO_JOGADOR;

ALTER TABLE DIRETOR DROP CONSTRAINT FK_TIME_DIRETOR;
ALTER TABLE DIRETOR ADD CONSTRAINT FK_TIME_DIRETOR FOREIGN KEY (TIME) REFERENCES TIME(NOME) ON DELETE CASCADE;

INSERT INTO DIRETOR (TIME, NOME) VALUES ('Palmeiras', 'Alberto');
INSERT INTO DIRETOR (TIME, NOME) VALUES ('Palmeiras', 'Rodrigo');
INSERT INTO DIRETOR (TIME, NOME) VALUES ('São Paulo', 'Rodrigo');

SELECT * FROM DIRETOR;

INSERT INTO UNIFORME (TIME, TIPO, COR_PRINCIPAL) VALUES ('Palmeiras', 'titular', 'rosa');
INSERT INTO UNIFORME (TIME, TIPO, COR_PRINCIPAL) VALUES ('Palmeiras', 'reserva', 'azul');
INSERT INTO UNIFORME (TIME, TIPO, COR_PRINCIPAL) VALUES ('São Paulo', 'titular', 'preta');

SELECT * FROM UNIFORME;


