CREATE TABLE alunos(

    NUSP NUMBER(10) PRIMARY KEY,
    CPF NUMBER(11),
    NOME VARCHAR(50),
    CIDADE VARCHAR(25),
    ANOING NUMBER(4)

);

INSERT INTO ALUNOS (NUSP, CPF, NOME, CIDADE, ANOING) VALUES (1, 11122233344, 'ANA', 'ARARAQUARA', 2016);

INSERT INTO ALUNOS (NUSP, CPF, NOME, CIDADE, ANOING) VALUES (2, 11122233345 , 'ZÉ', 'SÃO CARLOS', 2017);

SELECT NOME, CIDADE FROM ALUNOS;

SELECT * FROM ALUNOS;

SELECT NOME FROM ALUNOS WHERE ANOING >= 2017;

